// code generated by [generate-resource-dart-code] vscode-extension.
class AssetsImages {
  static const android12splashPng = 'assets/images/android12splash.png';
  static const backgroundPng = 'assets/images/background.png';
}

class AssetsSvgs {

}

